# Generated by Django 2.0.5 on 2018-05-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180523_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('radio', 'Radio')], default='radio', max_length=200),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
