# Generated by Django 2.0.5 on 2018-05-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20180523_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='choice',
        ),
    ]
